name: Basic Workflow

on:
  push:
    branches:
      - main

  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show event name 
        run: echo "event name is:" ${{ github.event_name }} # This will print the event name that triggered the workflow, refer to Github Context from slides