name: Basic Workflow

on:
  push:
    branches:     # This workflow will run on push and pull request to the main branch
      - main

  pull_request: 
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3